In [2]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [3]:
filenames = []
for file in os.listdir('t20'):
    filenames.append(os.path.join('t20',file))

In [4]:
filenames[0:5]

['t20\\1072317.yaml',
 't20\\1072318.yaml',
 't20\\1072319.yaml',
 't20\\1072320.yaml',
 't20\\1072321.yaml']

In [ ]:
final_df = pd.DataFrame()
counter = 1
for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter+=1
        
final_df

  7%|▋         | 149/2023 [00:21<09:01,  3.46it/s]

In [5]:
backup=final_df.copy()

NameError: name 'final_df' is not defined

In [7]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [ ]:
final_df

In [9]:
final_df['info.gender'].value_counts()

info.gender
male      1307
female     716
Name: count, dtype: int64

In [10]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_23648\2142223783.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.gender'],inplace=True)

,innings,info.balls_per_over,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.players.England,info.players.Australia,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hobart,[2018-02-07],T20,Australia,20,[GJ Maxwell],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, MP...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'England', 'deliveri...",6,NaN,[2018-02-10],T20,Australia,20,[KW Richardson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Wellington,[2018-02-13],T20,New Zealand,20,[KS Williamson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Auckland,[2018-02-16],T20,Australia,20,[DJM Short],NaN,"[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hamilton,[2018-02-18],T20,England,20,[EJG Morgan],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],T20,Pakistan,20,[Umar Akmal],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],T20,India,20,[S Dhawan],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],T20,Netherlands,20,[Mudassar Bukhari],NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
2021,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],T20,Australia,20,[GJ Maxwell],NaN,"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],T20,Australia,20,[GJ Maxwell],NaN,"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_23648\3157072726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,info.balls_per_over,info.city,info.dates,info.outcome.winner,info.player_of_match,info.players.England,info.players.Australia,info.registry.people.AC Agar,info.registry.people.AD Hales,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hobart,[2018-02-07],Australia,[GJ Maxwell],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, MP...",a2421394,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'England', 'deliveri...",6,NaN,[2018-02-10],Australia,[KW Richardson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",a2421394,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Wellington,[2018-02-13],New Zealand,[KS Williamson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...",NaN,NaN,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Auckland,[2018-02-16],Australia,[DJM Short],NaN,"[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",a2421394,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hamilton,[2018-02-18],England,[EJG Morgan],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...",NaN,NaN,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],Pakistan,[Umar Akmal],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],India,[S Dhawan],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],Netherlands,[Mudassar Bukhari],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
2021,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],Australia,[GJ Maxwell],NaN,"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],Australia,[GJ Maxwell],NaN,"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [13]:
matches = pickle.load(open('dataset_level1.pkl','rb'))

In [14]:
matches

,innings,info.balls_per_over,info.city,info.dates,info.outcome.winner,info.player_of_match,info.players.England,info.players.Australia,info.registry.people.AC Agar,info.registry.people.AD Hales,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hobart,[2018-02-07],Australia,[GJ Maxwell],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, MP...",a2421394,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'England', 'deliveri...",6,NaN,[2018-02-10],Australia,[KW Richardson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...","[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",a2421394,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Wellington,[2018-02-13],New Zealand,[KS Williamson],"[JJ Roy, AD Hales, DJ Malan, JM Vince, JC Butt...",NaN,NaN,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'New Zealand', 'deli...",6,Auckland,[2018-02-16],Australia,[DJM Short],NaN,"[DA Warner, DJM Short, CA Lynn, GJ Maxwell, AJ...",a2421394,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'England', 'deliveri...",6,Hamilton,[2018-02-18],England,[EJG Morgan],"[JJ Roy, AD Hales, DJ Malan, EJG Morgan, JC Bu...",NaN,NaN,92aeac25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Mirpur,[2016-03-04],Pakistan,[Umar Akmal],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,Mirpur,[2016-03-06],India,[S Dhawan],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,Dubai,[2016-02-03],Netherlands,[Mudassar Bukhari],NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
2021,"[{'1st innings': {'team': 'Australia', 'delive...",6,NaN,[2016-09-06],Australia,[GJ Maxwell],NaN,"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,Colombo,[2016-09-09],Australia,[GJ Maxwell],NaN,"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN