In [1]:
import pandas as pd
import pickle
import numpy as np

In [2]:
df=pickle.load(open('dataset_level2.pkl','rb'))

In [3]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                7922
venue                  0
dtype: int64

In [4]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        2841
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1328
Sydney Cricket Ground                       623
Adelaide Oval                               373
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: count, dtype: int64

In [5]:
cities = np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [6]:

df['city'] = cities

In [7]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [8]:

df.drop(columns=['venue'],inplace=True)

In [9]:

df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,England,Australia,0.1,2,0,Hobart
1,2,England,Australia,0.2,0,0,Hobart
2,2,England,Australia,0.3,1,0,Hobart
3,2,England,Australia,0.4,4,0,Hobart
4,2,England,Australia,0.5,2,0,Hobart
...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo

In [10]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [11]:

df = df[df['city'].isin(eligible_cities)]

In [12]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
124,3,England,Australia,0.1,2,0,Melbourne
125,3,England,Australia,0.2,1,0,Melbourne
126,3,England,Australia,0.3,0,0,Melbourne
127,3,England,Australia,0.4,1,0,Melbourne
128,3,England,Australia,0.5,3,0,Melbourne
...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo

In [13]:
df['runs'] = pd.to_numeric(df['runs'], errors='coerce')

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\3344088627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runs'] = pd.to_numeric(df['runs'], errors='coerce')

In [14]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\190681986.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [15]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
124,3,England,Australia,0.1,2,0,Melbourne,2
125,3,England,Australia,0.2,1,0,Melbourne,3
126,3,England,Australia,0.3,0,0,Melbourne,3
127,3,England,Australia,0.4,1,0,Melbourne,4
128,3,England,Australia,0.5,3,0,Melbourne,7
...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [16]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\2777558413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\2777558413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
124,3,England,Australia,0.1,2,0,Melbourne,2,0,1
125,3,England,Australia,0.2,1,0,Melbourne,3,0,2
126,3,England,Australia,0.3,0,0,Melbourne,3,0,3
127,3,England,Australia,0.4,1,0,Melbourne,4,0,4
128,3,England,Australia,0.5,3,0,Melbourne,7,0,5
...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7

In [17]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')
df

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\562775579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
124,3,England,Australia,0.1,2,0,Melbourne,2,0,1,1
125,3,England,Australia,0.2,1,0,Melbourne,3,0,2,2
126,3,England,Australia,0.3,0,0,Melbourne,3,0,3,3
127,3,England,Australia,0.4,1,0,Melbourne,4,0,4,4
128,3,England,Australia,0.5,3,0,Melbourne,7,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121

In [18]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\2304996896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - df['balls_bowled']
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\2304996896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
124,3,England,Australia,0.1,2,0,Melbourne,2,0,1,1,119
125,3,England,Australia,0.2,1,0,Melbourne,3,0,2,2,118
126,3,England,Australia,0.3,0,0,Melbourne,3,0,3,3,117
127,3,England,Australia,0.4,1,0,Melbourne,4,0,4,4,116
128,3,England,Australia,0.5,3,0,Melbourne,7,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2
156509,1305,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0

In [19]:

df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
# Convert to numeric (already int, but safe)
df['player_dismissed'] = df['player_dismissed'].astype(int)

# Groupwise cumulative sum only on that column
df['player_dismissed_cum'] = df.groupby('match_id')['player_dismissed'].cumsum()

# Wickets left
df['wickets_left'] = 10 - df['player_dismissed_cum']

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1122442204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1122442204.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].astype(int)
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1122442204.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed_cum'] = df.groupby('match_id')['player_dismissed'].cumsum()
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1122442204.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left'] = 10 - df['player_dismissed_cum']

In [20]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,player_dismissed_cum,wickets_left
124,3,England,Australia,0.1,2,0,Melbourne,2,0,1,1,119,0,10
125,3,England,Australia,0.2,1,0,Melbourne,3,0,2,2,118,0,10
126,3,England,Australia,0.3,0,0,Melbourne,3,0,3,3,117,0,10
127,3,England,Australia,0.4,1,0,Melbourne,4,0,4,4,116,0,10
128,3,England,Australia,0.5,3,0,Melbourne,7,0,5,5,115,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3,8,2
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2,8,2
156509,1305,Sri Lanka,Australia,19.5,0,1,Colombo,125,19,5,119,1,9,1
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0,9,1
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0,9,1

In [21]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\914577034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [22]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,player_dismissed_cum,wickets_left,crr
124,3,England,Australia,0.1,2,0,Melbourne,2,0,1,1,119,0,10,12.000000
125,3,England,Australia,0.2,1,0,Melbourne,3,0,2,2,118,0,10,9.000000
126,3,England,Australia,0.3,0,0,Melbourne,3,0,3,3,117,0,10,6.000000
127,3,England,Australia,0.4,1,0,Melbourne,4,0,4,4,116,0,10,6.000000
128,3,England,Australia,0.5,3,0,Melbourne,7,0,5,5,115,0,10,8.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156507,1305,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3,8,2,6.410256
156508,1305,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2,8,2,6.355932
156509,1305,Sri Lanka,Australia,19.5,0,1,Colombo,125,19,5,119,1,9,1,6.302521
156510,1305,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0,9,1,6.350000
156511,1305,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0,9,1,6.347107

In [23]:
df['match_id'] = df['match_id'].astype(int)
df['runs'] = pd.to_numeric(df['runs'], errors='coerce')
groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []
for id in match_ids:
    run_series = groups.get_group(id)['runs']  
    last_five.extend(run_series.rolling(window=30).sum().values.tolist())

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1404311638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['match_id'] = df['match_id'].astype(int)
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1404311638.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['runs'] = pd.to_numeric(df['runs'], errors='coerce')

In [24]:
df['last_five'] = last_five

C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_3220\1595651733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = last_five

In [25]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [26]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [27]:
final_df.dropna(inplace=True)

In [28]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [29]:
final_df = final_df.sample(final_df.shape[0])

In [30]:

final_df.sample(2)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
24693,Sri Lanka,New Zealand,Auckland,115,13,2,6.448598,49.0,115
4609,Pakistan,West Indies,Karachi,118,47,9,9.698630,53.0,205

In [31]:

X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [32]:

X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
32384,Sri Lanka,India,Colombo,152,17,6,8.854369,55.0
2215,England,India,Manchester,61,75,9,8.133333,39.0
43549,Pakistan,Bangladesh,Mirpur,61,71,9,7.469388,35.0
57521,India,Bangladesh,Dhaka,98,29,6,6.461538,46.0
56362,New Zealand,Pakistan,Chandigarh,62,76,9,8.454545,43.0
...,...,...,...,...,...,...,...,...
27120,Bangladesh,Pakistan,Cape Town,61,73,9,7.787234,43.0
15533,England,West Indies,Bridgetown,36,87,9,6.545455,31.0
29842,England,Pakistan,London,63,85,8,10.800000,54.0
21427,Pakistan,West Indies,Karachi,171,2,3,8.694915,58.0
3182,India,South Africa,Cape Town,49,89,9,9.483871,44.0

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [49]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [50]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [51]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9874441027641296
1.7698639631271362

In [53]:
pickle.dump(pipe,open('pipe3.pkl','wb'))

In [48]:
teams

NameError: name 'teams' is not defined